services:

  localstack:
    container_name: aws-local
    image: docker.io/localstack/localstack:4.0.2
    pull_policy: missing
    ports:
      - 4566:4566
    environment:
      - DEFAULT_REGION=us-east-1
      - SERVICES=sqs,s3
    healthcheck:
      interval: 15s

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: image_poster
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/.docker/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U local"]
      interval: 1s
      timeout: 5s
      retries: 5

  app-go:
    container_name: app-go
    image: app-go:latest
    build:
      context: ./app-go
      dockerfile: Dockerfile
    command: /app-go
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - localstack
    environment:
      APP_ENVIRONMENT: development
      HTTP_ADDRESS: 0.0.0.0:4000
      AWS_ENDPOINT_URL_S3: http://localstack:4566
      AWS_ENDPOINT_URL_SQS: http://localstack:4566
      POSTGRES_CONNECTION_STRING: host=postgres user=local password=local dbname=image_poster port=5432 sslmode=disable 