services:

  localstack:
    container_name: aws-local
    image: docker.io/localstack/localstack:4.0.2
    pull_policy: missing
    ports:
      - 4566:4566
    environment:
      - DEFAULT_REGION=us-east-1
      - SERVICES=sqs,s3
    healthcheck:
      interval: 15s

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: image_poster
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/.docker/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U local"]
      interval: 1s
      timeout: 5s
      retries: 5